delete http://localhost:3001/api/persons/68a71b22d8b672316a472b6d

post http://localhost:3001/api/persons 
Content-type: application/json

{
    "name": "Aasds Lovelace",
    "number": "39-44-5323523"
}
